#version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres-1  # Explicitly set container name
    environment:
      POSTGRES_DB: club_registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shyam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-1  # Explicitly set container name
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: club_registration
      DB_PASSWORD: shyam
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379
      PORT: 5000
      JWT_SECRET: super_secret_key_123456
      JWT_REFRESH_SECRET: your_jwt_refresh_secret_123456
      EMAIL_USER: psg.clubs.association@gmail.com
      EMAIL_PASS: omcvgcujnhmpunjx

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  pgdata:
  redisdata: