name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: shyamgk/club-backend:latest

      # Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: shyamgk/club-frontend:latest

      # Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 10.1.10.181
          username: suclub
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Navigate to project directory
            cd /home/suclub/project_clubs-backend

            # Pull the latest docker-compose.yml (if updated)
            git pull origin main

            # Pull the latest images
            docker-compose pull

            # Restart the containers
            docker-compose up -d --build